ALTER TABLE "photo_gallery_photos" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "photo_gallery_photos" ALTER COLUMN "id" SET DEFAULT GENERATED BY DEFAULT AS IDENTITY;--> statement-breakpoint
ALTER TABLE "photo_gallery_users" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "photo_gallery_users" ALTER COLUMN "id" SET DEFAULT GENERATED BY DEFAULT AS IDENTITY;--> statement-breakpoint
ALTER TABLE "photo_gallery_users" ALTER COLUMN "hashedRefreshToken" DROP NOT NULL; --> statement-breakpoint